### ISSUE TITLE
reCaptcha

### ISSUE THREAD

**Issue by umutcandev** [mertcangokgoz/simple-url-shortener#25]
reCapthca konfigürasyonunu hangi dosya üzerinden yapmalıyız?

**Comment by mertcangokgoz** [comment]
Merhaba

Statik olarak tanımlamışız zamanında https://github.com/mertcangokgoz/simple-url-shortener/blob/5873ff639936c9730e4b919ee8757d52a7eed8d2/login.php#L23 içerisinde bulabilirsiniz.
